BE-U1-W2-D3/Models/Biglietto.cs
namespace BE_U1_W2_D3.Models
{
    public class Biglietto
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Sala Sala { get; set; }
        public bool isRidotto { get; set; }

    }
}

BE-U1-W2-D3/Models/BigliettoAdd.cs
using System.ComponentModel.DataAnnotations;

namespace BE_U1_W2_D3.Models
{
    public class BigliettoAdd
    {
        [Display(Name = "Name")]
        [Required(ErrorMessage = "Il nome è obbligatorio!")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Il nome deve contenere minimo 2 e massimo 20 caratteri")]
        public string Nome { get; set; }

        [Display(Name = "Cognome")]
        [Required(ErrorMessage = "Il Cognome è obbligatorio!")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Il nome deve contenere minimo 2 e massimo 20 caratteri")]
        public string Cognome { get; set; }

        [Display(Name = "Sala")]
        [Required(ErrorMessage = "Seleziona una sala!")]
        public Sala Sala { get; set; }

        public bool isRidotto { get; set; }
    }
}

BE-U1-W2-D3/Models/BigliettoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BE_U1_W2_D3.Models
{
    public class BigliettoViewModel
    {
        public List<Biglietto> Biglietti { get; set; } = new List<Biglietto>();
        public List<Sala> Sale { get; set; } = new List<Sala>();
    }
}

BE-U1-W2-D3/Models/ErrorViewModel.cs
namespace BE_U1_W2_D3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BE-U1-W2-D3/Models/Sala.cs
using System.ComponentModel.DataAnnotations;

namespace BE_U1_W2_D3.Models
{
    public class Sala
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public int PostiTotali { get; set; } = 120;
        public int BigliettiVenduti { get; set; } = 0;
        public int BigliettiRidotti { get; set; } = 0;
    }
}

BE-U1-W2-D3/Models/SalaViewModel.cs
namespace BE_U1_W2_D3.Models
{
    public class SalaViewModel
    {

    }
}

BE-U1-W2-D3/Controllers/BigliettiController.cs
using BE_U1_W2_D3.Models;
using Microsoft.AspNetCore.Mvc;

namespace BE_U1_W2_D3.Controllers
{
    public class BigliettiController : Controller
    {
        private static List<Biglietto> biglietti = new List<Biglietto>();
        public static List<Sala> sale = new List<Sala>
        {
            new Sala() {Id=Guid.NewGuid(), Nome = "SALA NORD"},
            new Sala() {Id=Guid.NewGuid(), Nome = "SALA EST"},
            new Sala() {Id=Guid.NewGuid(), Nome = "SALA SUD"}
        };

        public IActionResult Index()
        {
            var viewModel = new Biglietto();

            ViewBag.Sale = sale;
            ViewBag.Biglietti = biglietti;
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Acquista(Biglietto biglietto)
        {
            var sala = sale.FirstOrDefault(s => s.Id == biglietto.Sala?.Id);

            if (sala != null && sala.PostiTotali > 0)
            {
                sala.PostiTotali--;

                if (!biglietto.isRidotto)
                {
                    sala.BigliettiVenduti++;
                }
                else
                {
                    sala.BigliettiRidotti++;
                }

                biglietti.Add(new Biglietto
                {
                    Id = Guid.NewGuid(),
                    Nome = biglietto.Nome,
                    Cognome = biglietto.Cognome,
                    Sala = sala,
                    isRidotto = biglietto.isRidotto
                });
            }

            return RedirectToAction("Index");
        }
    }
}

BE-U1-W2-D3/Controllers/HomeController.cs
using System.Diagnostics;
using BE_U1_W2_D3.Models;
using Microsoft.AspNetCore.Mvc;


namespace BE_U1_W2_D3.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BE-U1-W2-D3/Views/Biglietti/Index.cshtml
@using BE_U1_W2_D3.Models
@model Biglietto

@{
    ViewData["Title"] = "Home Page";
}

<h2>Acquista biglietti</h2>

<div>
    <form asp-controller="Biglietti" asp-action="Acquista" method="post">
        <div class="form-group">
            <label asp-for="Nome">Nome</label>
            <input asp-for="Nome" class="form-control" required />
        </div>
        <div class="form-group">
            <label asp-for="Cognome">Cognome</label>
            <input asp-for="Cognome" class="form-control" required />
        </div>
        <div class="form-group">
            <label asp-for="Sala.Id">Sala</label>
            <select asp-for="Sala.Id" class="form-control">
                <option value="">Seleziona una sala</option>
                @foreach (var sala in ViewBag.Sale)
                {
                    <option value="@sala.Id">@sala.Nome</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="isRidotto">Ridotto?</label>
            <input asp-for="isRidotto" type="checkbox" />
        </div>
        <button type="submit" class="btn btn-primary">Acquista</button>
    </form>
</div>

<h3>Biglietti Rimanenti</h3>
<table class="table">
    <thead>
        <tr>
            <th>Totali</th>
            <th>Interi</th>
            <th>Ridotti</th>
            <th>Sala</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var biglietto in ViewBag.Sale)
        {
            <tr>
                <td>@biglietto.PostiTotali</td>
                <td>@biglietto.BigliettiVenduti</td>
                <td>@biglietto.BigliettiRidotti</td>
                <td>@biglietto.Nome</td>
            </tr>
        }
    </tbody>
</table>

<h3>Biglietti Acquistati</h3>
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Sala</th>
            <th>Ridotto</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var biglietto in ViewBag.Biglietti)
        {
            <tr>
                <td>@biglietto.Nome</td>
                <td>@biglietto.Cognome</td>
                <td>@biglietto.Sala.Nome</td>
                <td>@(biglietto.isRidotto ? "Si" : "No")</td>
            </tr>
        }
    </tbody>
</table>

BE-U1-W2-D3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BE-U1-W2-D3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BE_U1_W2_D3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BE_U1_W2_D3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BE_U1_W2_D3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biglietti" asp-action="Index">Cinema</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BE_U1_W2_D3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>